# Generated by Django 5.1.4 on 2025-01-13 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petphoto",
            name="create_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="petphoto",
            name="modified_ad",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
